## Aave Metis V3

_Updated as of block [17173375](https://etherscan.io/block/17173375) at 5/2/2023, 9:26:11 AM ET_

- ID: 212
- Proposer: [0xf71fc92e2949ccF6A5Fd369a0b402ba80Bc61E02](https://etherscan.io/address/0xf71fc92e2949ccF6A5Fd369a0b402ba80Bc61E02)
- Start Block: 17171763 (5/2/2023, 3:59:23 AM ET)
- End Block: 17190963 (5/5/2023, 12:56:55 AM ET)
- Targets: [0x2fE52eF191F0BE1D98459BdaD2F1d3160336C08f](https://etherscan.io/address/0x2fE52eF191F0BE1D98459BdaD2F1d3160336C08f#code)
- Executor: [0xEE56e2B3D491590B5b31738cC34d5232F378a8D5](https://etherscan.io/address/0xEE56e2B3D491590B5b31738cC34d5232F378a8D5) (Short executor)
- Simulation: [https://dashboard.tenderly.co/me/simulator/3b3d597b-3fea-4103-a32f-bd9e0f6967ce](https://dashboard.tenderly.co/me/simulator/3b3d597b-3fea-4103-a32f-bd9e0f6967ce)

<details>
  <summary>Proposal text</summary>

# Summary

This proposal allows the Aave governance to activate the Aave V3 Metis pool (3.0.2) by completing all the initial setup and listing WETH, USDC, USDT, DAI, and METIS as suggested by the risk service providers (Gauntlet and Chaos Labs) on the [governance forum](https://governance.aave.com/t/launch-aave-v3-on-metis/7056/78).
All the Aave Metis V3 addresses can be found in the [aave-address-book](https://github.com/bgd-labs/aave-address-book/blob/main/src/AaveV3Metis.sol).

# Motivation

All the governance procedures for the expansion of Aave v3 to Metis have been finished, said:

- Positive signaling and approval regarding the expansion on the [governance forum](https://governance.aave.com/t/launch-aave-v3-on-metis/7056), [temp check snapshot](https://snapshot.org/#/aave.eth/proposal/0xaba8da3287788ee77013aa6b0584694807dc15304ab5c283fe1fc728bf1d5864), and [final snapshot](https://snapshot.org/#/aave.eth/proposal/0x7e6175c21342dbd88dc5b0dabf2d0a86339e3ef3f199fc7d778a9a6f05ed0df9).
- Positive technical evaluation done by BGD Labs of the Metis network, as described in the [forum](https://governance.aave.com/t/bgd-aave-metis-infrastructure-technical-evaluation/11374) in detail.
- Positive risk analysis and assets/parameters recommendation by the risk providers Chaos Labs and Gauntlet, as commented on the [forum](https://governance.aave.com/t/launch-aave-v3-on-metis/7056/78).

# Specification

This proposal's payload does the following: grants `POOL_ADMIN` permissions to all the asset listing Stewards created inside the `constructor()` of the payload via `ACL_MANAGER.addPoolAdmin(stewards[i])`

The Steward pattern is taken from [V3-listing stewards](https://github.com/bgd-labs/aave-v3-listing-stewards/blob/feat/v3-ethereum-tests/src/contracts/common/StewardBase.sol#L8), already used for the activation of Aave V3 Ethereum. Each Steward will handle the listing of one specific asset and then renounce to the granted `POOL_ADMIN` role. This process is needed as otherwise, the proposal's gas limit would be really high.

The pool activation will be done via the cross-chain governance with the help of cross-chain forwarder on Ethereum, which on a successful vote by the community, will trigger queuing of the payload action on Metis, which later could be executed by anyone.

## Configuration snapshot

What you can see here is a formatted excerpt of the configuration snapshot with the relevant configurations after proposal execution. Although stable borrowing is disabled for all the respective assets, interest rate parameters for stable borrowing have been configured according to the values set in [Aave V3 Ethereum](https://github.com/bgd-labs/aave-v3-ethereum-proposal/blob/main/src/contracts/AaveV3EthereumRateStrategiesDefinition.sol). You can find the complete snapshot in the proposal [repository](https://github.com/bgd-labs/aave-v3-metis-proposal/blob/main/reports/post-stewards-aave-v3-metis.json).

### Reserve Configurations

| symbol                                                                                          | ltv    | liqThreshold | liqBonus | liqProtocolFee | reserveFactor | borrowingEnabled | collateralEnabled | stableBorrowing | borrowableInIsolation | supplyCap      | borrowCap      | isFlashloanable |
| ----------------------------------------------------------------------------------------------- | ------ | ------------ | -------- | -------------- | ------------- | ---------------- | ----------------- | --------------- | --------------------- | -------------- | -------------- | --------------- |
| [WETH](https://andromeda-explorer.metis.io/address/0x420000000000000000000000000000000000000A)  | 80.00% | 82.50%       | 7.50%    | 10%            | 15%           | true             | true              | false           | false                 | 50 WETH        | 30 WETH        | true            |
| [USDC](https://andromeda-explorer.metis.io/address/0xEA32A96608495e54156Ae48931A7c20f0dcc1a21)  | 80.00% | 85.00%       | 5.00%    | 10%            | 10%           | true             | true              | false           | true                  | 1'200'000 USDC | 1'200'000 USDC | true            |
| [DAI](https://andromeda-explorer.metis.io/address/0x4c078361FC9BbB78DF910800A991C7c3DD2F6ce0)   | 75.00% | 80.00%       | 5.00%    | 10%            | 10%           | true             | true              | false           | false                 | 950'000 DAI    | 950'000 DAI    | true            |
| [USDT](https://andromeda-explorer.metis.io/address/0xbB06DCA3AE6887fAbF931640f67cab3e3a16F4dC)  | 75.00% | 80.00%       | 5.00%    | 10%            | 10%           | true             | true              | false           | true                  | 1'400'000 USDT | 1'400'000 USDT | true            |
| [METIS](https://andromeda-explorer.metis.io/address/0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000) | N/A    | N/A          | N/A      | N/A            | 15%           | true             | false             | false           | false                 | 7'500 METIS    | 4'000 METIS    | true            |

### InterestRateStrategies

| assets | baseVariableBorrowRate | variableRateSlope1 | variableRateSlope2 | optimalUsageRatio |
| ------ | ---------------------- | ------------------ | ------------------ | ----------------- |
| WETH   | 1%                     | 3.80%              | 80.00%             | 80.00%            |
| USDC   | 0%                     | 4.00%              | 60.00%             | 90.00%            |
| DAI    | 0%                     | 7.00%              | 75.00%             | 80.00%            |
| USDT   | 0%                     | 4.00%              | 75.00%             | 80.00%            |
| METIS  | 0%                     | 7.00%              | 300.00%            | 45.00%            |

## Security procedures

The proposal execution is simulated [within the tests](https://github.com/bgd-labs/aave-v3-metis-proposal/blob/main/tests/AaveV3MetisPool.t.sol) and the resulting pool configuration is tested for correctness.

The deployed pool and other permissions have been programmatically verified.

In addition, we have also checked the code diffs of the deployed metis contracts with the deployed contracts on Ethereum and other networks.

As a matter of caution, the `POOL_ADMIN` role will be given for the first weeks to the Aave Guardian multisig.

## Deployed Contracts

- [ProposalPayload](https://andromeda-explorer.metis.io/address/0xF7780A54Ee6f99EE9C028ae552149CFbDDbaDfc4)

## References

- [Discussion: asset listings & parameters](https://governance.aave.com/t/launch-aave-v3-on-metis/7056/77)
- [Code: ProposalPayloadActivation](https://github.com/bgd-labs/aave-v3-metis-proposal/)

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

</details>

### Checks

#### Reports all state changes from the proposal ✅ Passed

Info:

- State changes:

```diff
# CanonicalTransactionChain at `0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9`
@@ Slot `0x885ae911a91d52ba03e9fc7b77c4d6ae755c0740e76634b4c2ab9cdabf358bf9` @@
- "0x0000000000000000000000000000000000000000000000000000000000000000"
+ "0xe55efb0d7b4434dfb2242d552b06859839684e09c9dd6f09a2da3373e85d7561"
@@ Slot `0x885ae911a91d52ba03e9fc7b77c4d6ae755c0740e76634b4c2ab9cdabf358bfa` @@
- "0x0000000000000000000000000000000000000000000000000000000000000000"
+ "0x0000000000000000000000000000000000000000000000010650350064559874"
@@ Slot `0xf2fadc8f281df3b2e312450efbc7e5145e4214fc70e639a3a1b10148ef5697af` @@
- "0x0000000000000000000000000000000000000000000000000000000000006734"
+ "0x0000000000000000000000000000000000000000000000000000000000006735"
```

#### Check stack trace of the proposal ✅ Passed

Info:

- There is no SELFDESTRUCT inside of delegated call

#### Reports all events emitted from the proposal ✅ Passed

Info:

- Events Emitted:
  - CanonicalTransactionChain at `0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9`
    - `TransactionEnqueued(_chainId: 1088, _l1TxOrigin: 0x192e1101855bd523ba69a9794e0217f0db633510, _target: 0x4200000000000000000000000000000000000007, _gasLimit: 5000000, _data: 0xcbd4ece90000000000000000000000008ec77963068474a45016938deb95e603ca82a029000000000000000000000000ee56e2b3d491590b5b31738cc34d5232f378a8d5000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000067340000000000000000000000000000000000000000000000000000000000000244d9a4cbdf00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f7780a54ee6f99ee9c028ae552149cfbddbadfc40000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000965786563757465282900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000, _queueIndex: 26420, _timestamp: 1683331188)`
  - Lib_ResolvedDelegateProxy at `0x081D1101855bD523bA69A9794e0217F0DB6323ff`
    - `SentMessage(target: 0x8ec77963068474a45016938deb95e603ca82a029, sender: 0xee56e2b3d491590b5b31738cc34d5232f378a8d5, message: 0xd9a4cbdf00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f7780a54ee6f99ee9c028ae552149cfbddbadfc400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000009657865637574652829000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001, messageNonce: 26420, gasLimit: 5000000, chainId: 1088)`

#### Check all targets are verified on Etherscan ✅ Passed

Info:

- Targets:
  - 0x2fE52eF191F0BE1D98459BdaD2F1d3160336C08f: Contract (not verified)

#### Check all touched contracts are verified on Etherscan ✅ Passed

Info:

- Touched address:
  - 0xD73a92Be73EfbFcF3854433A5FcbAbF9c1316073: EOA (verification not applicable)
  - 0xEC568fffba86c094cf06b22134B23074DFE2252c: Contract (verified) (AaveGovernanceV2)
  - 0xEE56e2B3D491590B5b31738cC34d5232F378a8D5: Contract (verified) (Executor)
  - 0xb7e383ef9B1E9189Fc0F71fb30af8aa14377429e: Contract (verified) (GovernanceStrategy)
  - 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9: Contract (verified) (InitializableAdminUpgradeabilityProxy)
  - 0x96F68837877fd0414B55050c9e794AECdBcfCA59: Contract (verified) (AaveTokenV2)
  - 0x2fE52eF191F0BE1D98459BdaD2F1d3160336C08f: Contract (not verified)
  - 0x081D1101855bD523bA69A9794e0217F0DB6323ff: Contract (verified) (Lib_ResolvedDelegateProxy)
  - 0x918778e825747a892b17C66fe7D24C618262867d: Contract (verified) (Lib_AddressManager)
  - 0x8bF439ef7167023F009E24b21719Ca5f768Ecb36: Contract (verified) (L1CrossDomainMessenger)
  - 0x7f6B0b7589febc40419a8646EFf9801b87397063: Contract (verified) (MVM_DiscountOracle)
  - 0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9: Contract (verified) (CanonicalTransactionChain)

#### Runs solc against the verified contracts ✅ Passed

Info:

-

<details>
<summary>View Details</summary>
<details>
<summary>View warnings for Lib_ResolvedDelegateProxy at `0x081D1101855bD523bA69A9794e0217F0DB6323ff`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

```

</details>

<details>
<summary>View warnings for CanonicalTransactionChain at `0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

```

</details>

<details>
<summary>View warnings for MVM_DiscountOracle at `0x7f6B0b7589febc40419a8646EFf9801b87397063`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

```

</details>

<details>
<summary>View warnings for InitializableAdminUpgradeabilityProxy at `0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9` with implementation AaveTokenV2 at `0x96F68837877fd0414B55050c9e794AECdBcfCA59`</summary>

```
ERROR:CryticCompile:Etherscan API rate limit exceeded
ERROR:CryticCompile:Etherscan api rate limit exceeded
```

</details>

<details>
<summary>View warnings for L1CrossDomainMessenger at `0x8bF439ef7167023F009E24b21719Ca5f768Ecb36`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

```

</details>

<details>
<summary>View warnings for Lib_AddressManager at `0x918778e825747a892b17C66fe7D24C618262867d`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

```

</details>

<details>
<summary>View warnings for AaveTokenV2 at `0x96F68837877fd0414B55050c9e794AECdBcfCA59`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.

```

</details>

<details>
<summary>View warnings for GovernanceStrategy at `0xb7e383ef9B1E9189Fc0F71fb30af8aa14377429e`</summary>

```
INFO:CryticCompile:solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
ERROR:CryticCompile:Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.

```

</details>

</details>

#### Runs slither against the verified contracts ✅ Passed

Info:

-

<details>
<summary>View Details</summary>

<details>
<summary>Slither report for Lib_ResolvedDelegateProxy at `0x081D1101855bD523bA69A9794e0217F0DB6323ff`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

Error in 0x081D1101855bD523bA69A9794e0217F0DB6323ff
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.


```

</details>

<details>
<summary>Slither report for CanonicalTransactionChain at `0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9`</summary>

```
Etherscan API rate limit exceeded
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 279, in compile
    raise InvalidCompilation("Etherscan api rate limit exceeded")
crytic_compile.platform.exceptions.InvalidCompilation: Etherscan api rate limit exceeded
Error in 0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 279, in compile
    raise InvalidCompilation("Etherscan api rate limit exceeded")
crytic_compile.platform.exceptions.InvalidCompilation: Etherscan api rate limit exceeded

```

</details>

<details>
<summary>Slither report for MVM_DiscountOracle at `0x7f6B0b7589febc40419a8646EFf9801b87397063`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

Error in 0x7f6B0b7589febc40419a8646EFf9801b87397063
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.


```

</details>

<details>
<summary>Slither report for InitializableAdminUpgradeabilityProxy at `0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9` with implementation AaveTokenV2 at `0x96F68837877fd0414B55050c9e794AECdBcfCA59`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.6.10' not installed (set by SOLC_VERSION). Run `solc-select install 0.6.10`.

Error in 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.6.10' not installed (set by SOLC_VERSION). Run `solc-select install 0.6.10`.


```

</details>

<details>
<summary>Slither report for L1CrossDomainMessenger at `0x8bF439ef7167023F009E24b21719Ca5f768Ecb36`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

Error in 0x8bF439ef7167023F009E24b21719Ca5f768Ecb36
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.


```

</details>

<details>
<summary>Slither report for Lib_AddressManager at `0x918778e825747a892b17C66fe7D24C618262867d`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.

Error in 0x918778e825747a892b17C66fe7D24C618262867d
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.8.9' not installed (set by SOLC_VERSION). Run `solc-select install 0.8.9`.


```

</details>

<details>
<summary>Slither report for AaveTokenV2 at `0x96F68837877fd0414B55050c9e794AECdBcfCA59`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.

Error in 0x96F68837877fd0414B55050c9e794AECdBcfCA59
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.


```

</details>

<details>
<summary>Slither report for GovernanceStrategy at `0xb7e383ef9B1E9189Fc0F71fb30af8aa14377429e`</summary>

```
solc-select is not installed.
Run "pip install solc-select" to enable automatic switch of solc versions
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.

Error in 0xb7e383ef9B1E9189Fc0F71fb30af8aa14377429e
Traceback (most recent call last):
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 163, in run_solc_standard_json
    solc_json_output = json.loads(stdout)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.2/libexec/lib/python3.11/site-packages/slither/__main__.py", line 87, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/etherscan.py", line 362, in compile
    solc_standard_json.standalone_compile(filenames, compilation_unit, working_dir=working_dir)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 66, in standalone_compile
    targets_json = run_solc_standard_json(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.11/site-packages/crytic_compile/platform/solc_standard_json.py", line 193, in run_solc_standard_json
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Traceback (most recent call last):
  File "/opt/homebrew/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 80, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 51, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: Version '0.7.5' not installed (set by SOLC_VERSION). Run `solc-select install 0.7.5`.


```

</details>

</details>
